-- 在master模式下创建t_project_product表
-- 参考test模式下表结构，去掉F_前缀

CREATE TABLE IF NOT EXISTS "master"."t_project_product" (
  "id" character varying(50) NOT NULL,
  "project_id" character varying(50),
  "product_type" character varying(100),
  "product_name" character varying(200),
  "product_standard_select" text,
  "product_standard" character varying(200),
  "procuring_entity" character varying(200),
  "manufacturer_id" character varying(200),
  "supplier_id" character varying(200),
  "seller" character varying(200),
  "address" character varying(500),
  "quantity" double precision,
  "unit" character varying(20),
  "record_no" character varying(100),
  "batch_date" timestamp without time zone,
  "batch_no" character varying(100),
  "unit_price" double precision,
  "approach_time" timestamp without time zone,
  "filling_time" timestamp without time zone,
  "check_status" integer,
  "supplier_check_status" integer,
  "check_out_time" integer,
  "check_first_fail_reason" character varying(500),
  "check_second_fail_reason" character varying(500),
  "check_first_fail_remark" text,
  "check_second_fail_remark" text,
  "supplier_check_first_fail_reason" character varying(500),
  "supplier_check_second_fail_reason" character varying(500),
  "supplier_check_first_fail_remark" text,
  "supplier_check_second_fail_remark" text,
  "certificate" text,
  "inspection_report" text,
  "performance_test_report" text,
  "physical_photo" text,
  "is_pass_by_request" integer,
  "sort_code" bigint,
  "jl_unit" character varying(200),
  "pass_reason" character varying(500),
  "jl_unit_check_time" timestamp without time zone,
  "enabled_mark" integer DEFAULT 1,
  "creator_user_id" character varying(50),
  "creator_time" timestamp without time zone,
  "last_modify_user_id" character varying(50),
  "last_modify_time" timestamp without time zone,
  "delete_user_id" character varying(50),
  "delete_time" timestamp without time zone,
  "delete_mark" integer DEFAULT 0,
  "project_progress" character varying(50),
  "send_flag" integer,
  "file_url" character varying(500),
  "has_record_no" integer,
  -- 审计字段 (按照database-rules.md规则添加)
  "tenant_id" varchar(50) DEFAULT '000000',
  "create_by" varchar(50),
  "create_time" timestamp DEFAULT now(),
  "update_by" varchar(50),
  "update_time" timestamp DEFAULT now(),
  "del_flag" integer DEFAULT 0,
  "create_dept" varchar(50) DEFAULT '103',
  PRIMARY KEY ("id")
);

COMMENT ON TABLE "master"."t_project_product" IS '项目建材产品表';
