INSERT INTO master.t_project (
    id,
    tenant_id,
    construction_permit,
    permit_issue_date,
    project_name,
    project_nature,
    building_area,
    project_progress,
    project_address,
    structure_type,
    quality_supervision_agency,
    construction_unit,
    construction_unit_manager,
    manager_contact,
    has_report,
    is_integrated,
    remarks,
    create_by,
    create_time,
    update_by,
    update_time,
    del_flag,
    create_dept
)
SELECT
    tp."F_Id"::varchar(50) AS id,
    COALESCE(NULLIF(tp."tenant_id", ''), '000000') AS tenant_id,
    tp."F_ConstructionPermit",
    tp."F_PermitIssueDate",
    tp."F_ProjectName",
    tp."F_ProjectNature",
    tp."F_BuildingArea",
    tp."F_ProjectProgress",
    tp."F_ProjectAddress",
    tp."F_StructureType",
    tp."F_QualitySupervisionAgency",
    tp."F_ConstructionUnit",
    tp."F_ConstructionUnitManager",
    tp."F_ManagerContact",
    tp."F_HasReport",
    tp."F_IsIntegrated",
    tp."F_Remarks",
    tp."F_CreatorUserId"::varchar(50),
    tp."F_CreatorTime",
    tp."F_LastModifyUserId"::varchar(50),
    tp."F_LastModifyTime",
    COALESCE(tp."F_DeleteMark", 0),
    COALESCE(NULLIF(tp."create_dept", ''), '103')
FROM test.t_project tp
ON CONFLICT (id, tenant_id) DO NOTHING;
