CREATE TABLE IF NOT EXISTS master.t_quality_trace (
    id varchar(50) PRIMARY KEY,
    original_id varchar(50),
    check_organize varchar(500),
    project_no varchar(100),
    project_name varchar(1000),
    product_name varchar(500),
    factory_name varchar(500),
    batch_no varchar(200),
    check_project_name varchar(500),
    data_status varchar(50),
    is_collect varchar(50),
    conclusion_mark varchar(50),
    conclusion text,
    report_time timestamp,
    check_time timestamp,
    enabled_mark integer,
    create_by varchar(50),
    create_time timestamp,
    update_by varchar(50),
    update_time timestamp,
    delete_by varchar(50),
    delete_time timestamp,
    del_flag integer DEFAULT 0
);
