INSERT INTO master.t_project (
    id,
    tenant_id,
    construction_permit,
    permit_issue_date,
    project_name,
    project_nature,
    building_area,
    project_progress,
    project_address,
    structure_type,
    quality_supervision_agency,
    construction_unit,
    construction_unit_manager,
    manager_contact,
    has_report,
    is_integrated,
    remarks,
    create_by,
    create_time,
    update_by,
    update_time,
    del_flag,
    create_dept
)
SELECT
    tp."F_Id"::varchar(50) AS id,
    '000000' AS tenant_id,
    tp."F_ConstructionPermitNo",
    tp."F_ConstructionPermitDate",
    tp."F_ProjectName",
    tp."F_ProjectProperties",
    tp."F_Floorage",
    tp."F_ProjectProgress",
    tp."F_ProjectAddress",
    tp."F_ProjectStructureType",
    tp."F_SupervisionOrganization",
    tp."F_ConstrctionUnitId",
    tp."F_ConstrctionUnitLeader",
    tp."F_ConstrctionUnitLeaderPhone",
    NULL,
    NULL,
    tp."F_Remark",
    tp."F_CreatorUserId"::varchar(50),
    tp."F_CreatorTime",
    tp."F_LastModifyUserId"::varchar(50),
    tp."F_LastModifyTime",
    COALESCE(tp."F_DeleteMark", 0),
    '103'
FROM test.t_project tp
ON CONFLICT (id, tenant_id) DO NOTHING;
