CREATE TABLE IF NOT EXISTS master.t_project (
    id varchar(50) NOT NULL,
    tenant_id varchar(20) NOT NULL DEFAULT '000000',
    construction_permit varchar(100),
    permit_issue_date timestamp,
    project_name varchar(500),
    project_nature varchar(100),
    building_area numeric(18,2),
    project_progress varchar(100),
    project_address varchar(1000),
    structure_type varchar(100),
    quality_supervision_agency varchar(500),
    construction_unit varchar(500),
    construction_unit_manager varchar(100),
    manager_contact varchar(50),
    has_report varchar(20),
    is_integrated varchar(20),
    remarks text,
    create_by varchar(50),
    create_time timestamp,
    update_by varchar(50),
    update_time timestamp,
    del_flag integer DEFAULT 0,
    create_dept varchar(50) DEFAULT '103',
    PRIMARY KEY (id, tenant_id)
);
