-- 将test.t_project_product表迁移到master.t_project_product表
-- 迁移规则参考: openspec/rules/database-rules.md
-- 关联关系参考: openspec/原型/数据库关联关系/1.备案产品和建材产品表.md

INSERT INTO "master"."t_project_product" (
    "id",
    "tenant_id",
    "project_id",
    "product_type",
    "product_name",
    "product_standard_select",
    "product_standard",
    "procuring_entity",
    "manufacturer_id",
    "supplier_id",
    "seller",
    "address",
    "quantity",
    "unit",
    "record_no",
    "batch_date",
    "batch_no",
    "unit_price",
    "approach_time",
    "filling_time",
    "check_status",
    "supplier_check_status",
    "check_out_time",
    "check_first_fail_reason",
    "check_second_fail_reason",
    "check_first_fail_remark",
    "check_second_fail_remark",
    "supplier_check_first_fail_reason",
    "supplier_check_second_fail_reason",
    "supplier_check_first_fail_remark",
    "supplier_check_second_fail_remark",
    "certificate",
    "inspection_report",
    "performance_test_report",
    "physical_photo",
    "is_pass_by_request",
    "sort_code",
    "jl_unit",
    "pass_reason",
    "jl_unit_check_time",
    "enabled_mark",
    "creator_user_id",
    "creator_time",
    "last_modify_user_id",
    "last_modify_time",
    "delete_user_id",
    "delete_time",
    "delete_mark",
    "project_progress",
    "send_flag",
    "file_url",
    "has_record_no",
    "create_by",
    "create_time",
    "update_by",
    "update_time",
    "del_flag",
    "create_dept"
)
SELECT
    "F_Id" AS "id",
    '000000' AS "tenant_id",
    "F_ProjectId" AS "project_id",
    "F_ProductType" AS "product_type",
    "F_ProductName" AS "product_name",
    "F_ProductStandardSelect" AS "product_standard_select",
    "F_ProductStandard" AS "product_standard",
    "F_ProcuringEntity" AS "procuring_entity",
    "F_ManufacturerId" AS "manufacturer_id",
    "F_SupplierId" AS "supplier_id",
    "F_Seller" AS "seller",
    "F_Address" AS "address",
    "F_Quantity" AS "quantity",
    "F_Unit" AS "unit",
    "F_RecordNo" AS "record_no",
    "F_BatchDate" AS "batch_date",
    "F_BatchNo" AS "batch_no",
    "F_UnitPrice" AS "unit_price",
    "F_ApproachTime" AS "approach_time",
    "F_FillingTime" AS "filling_time",
    "F_CheckStatus" AS "check_status",
    "F_SupplierCheckStatus" AS "supplier_check_status",
    "F_CheckOutTime" AS "check_out_time",
    "F_CheckFirstFailReason" AS "check_first_fail_reason",
    "F_CheckSecondFailReason" AS "check_second_fail_reason",
    "F_CheckFirstFailRemark" AS "check_first_fail_remark",
    "F_CheckSecondFailRemark" AS "check_second_fail_remark",
    "F_SupplierCheckFirstFailReason" AS "supplier_check_first_fail_reason",
    "F_SupplierCheckSecondFailReason" AS "supplier_check_second_fail_reason",
    "F_SupplierCheckFirstFailRemark" AS "supplier_check_first_fail_remark",
    "F_SupplierCheckSecondFailRemark" AS "supplier_check_second_fail_remark",
    "F_Certificate" AS "certificate",
    "F_InspectionReport" AS "inspection_report",
    "F_PerformanceTestReport" AS "performance_test_report",
    "F_PhysicalPhoto" AS "physical_photo",
    "F_IsPassByRequest" AS "is_pass_by_request",
    "F_SortCode" AS "sort_code",
    "F_JlUnit" AS "jl_unit",
    "F_PassReason" AS "pass_reason",
    "F_JlUnitCheckTime" AS "jl_unit_check_time",
    "F_EnabledMark" AS "enabled_mark",
    "F_CreatorUserId" AS "creator_user_id",
    "F_CreatorTime" AS "creator_time",
    "F_LastModifyUserId" AS "last_modify_user_id",
    "F_LastModifyTime" AS "last_modify_time",
    "F_DeleteUserId" AS "delete_user_id",
    "F_DeleteTime" AS "delete_time",
    COALESCE("F_DeleteMark", 0) AS "delete_mark",
    "F_ProjectProgress" AS "project_progress",
    "F_SendFlag" AS "send_flag",
    "F_FileUrl" AS "file_url",
    "F_HasRecordNo" AS "has_record_no",
    COALESCE("F_CreatorUserId", '')::varchar(50) AS "create_by",
    COALESCE("F_CreatorTime", NOW())::timestamp AS "create_time",
    COALESCE("F_LastModifyUserId", '')::varchar(50) AS "update_by",
    COALESCE("F_LastModifyTime", NOW())::timestamp AS "update_time",
    CASE WHEN COALESCE("F_DeleteMark", 0) = 1 THEN 2 ELSE 0 END AS "del_flag",
    '103' AS "create_dept"
FROM "test"."t_project_product";